spring.application.name=service-1
# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/blogs
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# ===============================
# LIQUIBASE
# ===============================
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# KEYCLOAK
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/blogs-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/blogs-app/protocol/openid-connect/certs
