# Database connection properties
url=jdbc:postgresql://localhost:5432/blogs
username=postgres
password=postgres
driver=org.postgresql.Driver

# Liquibase properties
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
